<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

/* enqueue script libraries */
function base_enqueue_scripts_styles() {

	$version = time(); // Always bust cache (dev)

	// Sayoshi font
	wp_enqueue_style('satoshi', '//api.fontshare.com/v2/css?f[]=satoshi@300,301,400,401,500,501,700,701&display=swap' , array(), '1.0.1', 'all');

    // Swiper carousel
    wp_enqueue_script('swiper-carousel', get_stylesheet_directory_uri() . '/assets/swiper/swiper-bundle.min.js', array(), '11.0.5', true);
    wp_enqueue_style('swiper-carousel', get_stylesheet_directory_uri() . '/assets/swiper/swiper-bundle.min.css', array(), '11.0.5');

	// Infinite Marquee
	wp_enqueue_script('infinite-marquee', get_stylesheet_directory_uri() . '/assets/infinite-marquee/infinite-marquee.bundle.js', array(), '1.0.13', true);
	wp_enqueue_style('infinite-marquee', get_stylesheet_directory_uri() . '/assets/infinite-marquee/infinite-marquee.min.css', array(), '1.0.13');

	//choices vanilla select
	wp_enqueue_script('choices', get_stylesheet_directory_uri() . '/assets/choices/choices.min.js', array(), '11.1.0', array('strategy' => 'defer', 'in_footer' => true));
	wp_enqueue_style('choices', get_stylesheet_directory_uri() . '/assets/choices/choices.min.css', array(), '11.1.0', 'all');
	wp_enqueue_style('custom-choices', get_stylesheet_directory_uri() . '/assets/choices/custom-choices.css', array(), '0.0.01' . $version, 'all');

    // Micromodal popups
    wp_enqueue_script('micromodal', get_stylesheet_directory_uri() . '/assets/micromodal/micromodal.min.js', array(), '0.4.10', true);

    // Readsmore functionality
    wp_enqueue_script('readsmore', get_stylesheet_directory_uri() . '/assets/readsmore/index.umd.js', array(), '2.5.1', true);

    // Custom theme script
	wp_enqueue_script('theme-script', get_stylesheet_directory_uri() . '/assets/script.js', array(), $version, true);

    // Main stylesheet
    wp_dequeue_style('generate-child');
    wp_enqueue_style('theme-style', get_stylesheet_directory_uri() . '/style.css', array(), '1.0.93');

    // Remove unused scripts
    wp_dequeue_script('jquery-migrate');

}
add_action('wp_enqueue_scripts', 'base_enqueue_scripts_styles'); 

//remove autogenerated paragraph tags from cf7
add_filter('wpcf7_autop_or_not', '__return_false');

//remove oembed author from preview links - external sites
function base_remove_oembed_author( $data ) {

    unset($data['author_url']);
    unset($data['author_name']);
    return $data;

}
add_filter( 'oembed_response_data', 'base_remove_oembed_author' );

/**
 * Get property featured image URL
 * Check for external gallery first, fallback to regular featured image
 * 
 * @param int $post_id The post ID
 * @return string|false The image URL or false if none found
 */
function get_property_featured_image_url($post_id = null) {
	if (!$post_id) {
		$post_id = get_the_ID();
	}
	
	// Check for external gallery (comma-separated URLs in textarea)
	$external_gallery = get_field('external_property_gallery', $post_id);
	if (!empty($external_gallery) && is_string($external_gallery)) {
		// Parse first URL from comma or newline separated list
		$urls = preg_split('/[,\r\n]+/', $external_gallery, -1, PREG_SPLIT_NO_EMPTY);
		$urls = array_map('trim', $urls);
		$urls = array_filter($urls);
		if (!empty($urls[0])) {
			return $urls[0];
		}
	}
	
	// Fallback to regular featured image
	$thumbnail_id = get_post_thumbnail_id($post_id);
	if ($thumbnail_id) {
		return wp_get_attachment_image_url($thumbnail_id, 'full');
	}
	
	return false;
}

/**
 * Get property featured image HTML
 * Check for external gallery first, fallback to regular featured image
 * 
 * @param int $post_id The post ID
 * @param string $size The image size
 * @param array $attr Additional attributes
 * @return string The image HTML
 */
function get_property_featured_image($post_id = null, $size = 'medium', $attr = array()) {
	if (!$post_id) {
		$post_id = get_the_ID();
	}
	
	// Check for external gallery (comma-separated URLs in textarea)
	$external_gallery = get_field('external_property_gallery', $post_id);
	if (!empty($external_gallery) && is_string($external_gallery)) {
		// Parse first URL from comma or newline separated list
		$urls = preg_split('/[,\r\n]+/', $external_gallery, -1, PREG_SPLIT_NO_EMPTY);
		$urls = array_map('trim', $urls);
		$urls = array_filter($urls);
		if (!empty($urls[0])) {
			$url = $urls[0];
			$alt = get_the_title($post_id);
			$class = isset($attr['class']) ? $attr['class'] : '';
			return '<img src="' . esc_url($url) . '" alt="' . esc_attr($alt) . '" class="' . esc_attr($class) . '" />';
		}
	}
	
	// Fallback to regular featured image
	return get_the_post_thumbnail($post_id, $size, $attr);
}

//preload banner media to improve preconnect LCP
function base_banner_preload_image() {
	
	//standard banner
	$banner_media = get_field('banner_media');

	if($banner_media) {

		$banner_background = $banner_media['background_image'] ?: null;

		if(!empty($banner_background)) {
					
			$image_url = wp_get_attachment_image_url($banner_background, 'full');
			$image_srcset = wp_get_attachment_image_srcset($banner_background, 'full');
			$image_sizes = wp_get_attachment_image_sizes($banner_background, 'full');

			echo '<link rel="preload" as="image" href="' . esc_url($image_url) . '" imagesrcset="' . esc_attr($image_srcset) . '" imagesizes="' . esc_attr($image_sizes) . '">';

		}

	}
	
}
add_action('wp_head', 'base_banner_preload_image', 20);

//global content buttons
function base_get_content_buttons($args = null) {
	
	//buttons classes
	if(!empty($args['class'])) $class = $args['class'];
		
	$buttons = 'element_buttons';
	$buttons_option = null;

	//button prefix for use in certain clone items
	if(!empty($args['prefix'])) $buttons = $args['prefix'] . $buttons;

	if(have_rows($buttons, $buttons_option)) :
				
		$content_buttons_output = '<div class="content-buttons ' . ((isset($class)) ? esc_attr($class) : null) . '">';

		while(have_rows($buttons, $buttons_option)) : the_row();
 
			$button_link = get_sub_field('button_link');
			$button_style = get_sub_field('button_style');

			if(!empty($button_link)) : 

					$content_buttons_output .= '<a class="content-button ' . esc_attr($button_style) . '" href="' . esc_url($button_link['url']) . '" ' . ((str_contains($button_link['url'], 'book-consultation')) ? 'data-micromodal-trigger="book-consultation"' : null) . ' target="' . esc_attr( (($button_link['target']) ? $button_link['target'] : '_self')) . '">'
						. '<span class="button-title">' . $button_link['title'] . '</span>'
						. (($button_link['target'] == '_blank') ? '<span class="screen-reader-text"> (opens in new tab)</span>' : null)
						. ((str_contains($button_style, 'link')) ? '<svg width="24" height="18" viewBox="0 0 24 18" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="0.4375" y="0.95166" width="22.7371" height="16.1089" rx="8.05444" fill="#A8C8D0"/><path d="M8.01123 8.50635C7.73509 8.50635 7.51123 8.73021 7.51123 9.00635C7.51123 9.28249 7.73509 9.50635 8.01123 9.50635L8.01123 8.50635ZM15.9543 9.3599C16.1496 9.16464 16.1496 8.84806 15.9543 8.65279L12.7723 5.47081C12.5771 5.27555 12.2605 5.27555 12.0652 5.47081C11.87 5.66608 11.87 5.98266 12.0652 6.17792L14.8937 9.00635L12.0652 11.8348C11.87 12.03 11.87 12.3466 12.0652 12.5419C12.2605 12.7371 12.5771 12.7371 12.7723 12.5419L15.9543 9.3599ZM8.01123 9.50635L15.6008 9.50635L15.6008 8.50635L8.01123 8.50635L8.01123 9.50635Z" fill="#0C1E21"/></svg>' : null)
						. '</a>';
				
			endif;

		endwhile;

		$content_buttons_output .= '</div>';

	endif;
	
	echo $content_buttons_output ?? null;
	
}

//global page banners  
function base_global_page_banner() {
	
	//standard page banner
	get_template_part( 'elements/page-banner' );
					
}
add_action( 'generate_after_header' , 'base_global_page_banner' , 15 );

//remove page titles but keep on category and blog page
add_filter('generate_show_title', function($show_title) {

	//show title on category and main blog page
	if(is_category() || is_home() || is_search()) {
		return true;
	}
	
	return false;

});

//remove wordpress elements for theme
function base_remove_elements_from_page() {
    
	//remove archive title 
	remove_action('generate_archive_title', 'generate_archive_title', 10);
	
	//remove search results title 
	remove_action('generate_before_loop', 'generate_do_search_results_title', 10);

};
add_action( 'wp', 'base_remove_elements_from_page');

//include page sections
function base_include_theme_elements() {
	
	$page_id = ((is_home() || is_category()) ? get_option('page_for_posts') : null);

	if (have_rows('page_sections', $page_id)) : 

		while (have_rows('page_sections', $page_id)): the_row();

			$layout = str_replace('_', '-', get_row_layout());
			$template_path = locate_template("elements/{$layout}.php");

			if ($template_path) {
				include $template_path;
			}

		endwhile;

	endif;
	
	
}
add_action('generate_after_main_content', 'base_include_theme_elements', 20);

//add post classes for article elements
function include_custom_article_classes( $classes ) {

	$post_type = get_post_type();

	if(is_singular('post') && $post_type === 'post')
		$classes[] = 'single-post-article';

	if(is_singular('page') && $post_type === 'page')
		$classes[] = 'single-page-article';

  	return $classes;

}
add_filter('post_class', 'include_custom_article_classes');


//include custom functions for hooks
include_once('includes/function-hooks.php');

//include new developments file for redirect and url rewriting
include_once('includes/new-developments.php');

//generatepress svg icons 
add_filter( 'generate_svg_icon', function( $output, $icon ) {
	
	if('arrow' === $icon) { 
		$output = '<svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="7.44141" cy="7.44141" r="7.44141" fill="#D3D3D3"/><path d="M4.06836 5.69824L7.17584 8.77544L10.3068 5.74401" stroke="#323232" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
	}

	if('menu-bars' === $icon) {
		$output = '<svg width="26" height="21" viewBox="0 0 26 21" fill="none" xmlns="http://www.w3.org/2000/svg">
					<rect width="26" height="3" fill="#DADADA"/>
					<rect y="9" width="26" height="3" fill="#DADADA"/>
					<rect y="18" width="26" height="3" fill="#DADADA"/>
					</svg>';
	}
	
    return $output;
	
}, 10, 2 );


//google maps API key for ACF fields
function google_maps_api_key() {
	
	acf_update_setting('google_api_key', 'AIzaSyBMeSqVGj5e8uXs04vDGCBvya6P_fGqBUY');
	
}
add_action('acf/init', 'google_maps_api_key');


//blog filters and results
function blog_filtering_options() {
	
	//prevent adding filters to anywhere else
	if(!is_category() && !is_home())
		return;
	
	//blog filtering
	get_template_part( 'elements/blog-filtering', 'section' );
	
}
add_action('generate_before_main_content', 'blog_filtering_options', 5);

// Contact Info Shortcode
function contact_info_shortcode( $atts = [], $content = '', $tag = '' ) {
	// Ensure ACF is available
	if ( ! function_exists( 'have_rows' ) ) {
		return '';
	}

	if ( ! have_rows( 'contact_information', 'option' ) ) {
		return '';
	}

	$output = '<ul class="contact-info">';

	while ( have_rows( 'contact_information', 'option' ) ) : the_row();
		$link = get_sub_field( 'contact_link' );
		if ( ! $link || ! is_array( $link ) ) {
			continue;
		}

		$url    = isset( $link['url'] ) ? trim( $link['url'] ) : '';
		$title  = isset( $link['title'] ) ? $link['title'] : '';
		$target = isset( $link['target'] ) ? $link['target'] : '';

		if ( ! $url || ! $title ) {
			continue;
		}

		$is_email = false;
		$is_phone = false;
		$href     = $url;

		// Robust detection + normalization
		$lower = strtolower( $url );
		if ( strpos( $lower, 'mailto:' ) !== false ) {
			$is_email = true;
			$href = $url;
		} else if ( strpos( $lower, 'tel:' ) !== false ) {
			$is_phone = true;
			$href = $url;
		} 

		// Icons
		$email_svg = '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none"><path d="M28.555 11.1677L16.555 3.16766C16.3907 3.05802 16.1975 2.99951 16 2.99951C15.8025 2.99951 15.6093 3.05802 15.445 3.16766L3.445 11.1677C3.30801 11.2591 3.19572 11.3829 3.11809 11.5281C3.04046 11.6733 2.99989 11.8355 3 12.0002V25.0002C3 25.5306 3.21071 26.0393 3.58579 26.4144C3.96086 26.7894 4.46957 27.0002 5 27.0002H27C27.5304 27.0002 28.0391 26.7894 28.4142 26.4144C28.7893 26.0393 29 25.5306 29 25.0002V12.0002C29.0001 11.8355 28.9595 11.6733 28.8819 11.5281C28.8043 11.3829 28.692 11.2591 28.555 11.1677ZM12.09 19.0002L5 24.0002V13.9414L12.09 19.0002ZM14.1362 20.0002H17.8638L24.9425 25.0002H7.0575L14.1362 20.0002ZM19.91 19.0002L27 13.9414V24.0002L19.91 19.0002Z" fill="#BFA570"/></svg>';
		$phone_svg = '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none"><path d="M4.99998 9.99854C4.99736 8.5332 5.52801 7.11675 6.49315 6.01416C7.45622 4.91407 8.78629 4.20047 10.2353 4.00732L10.2363 4.0083C10.4504 3.98217 10.6673 4.02517 10.8545 4.13232C11.0414 4.2394 11.1886 4.40448 11.2744 4.60205V4.60303L11.2803 4.61377L13.832 10.311V10.3218L13.915 10.5112C13.9807 10.6628 14.008 10.8291 13.9941 10.9937C13.9802 11.1581 13.925 11.3163 13.8349 11.4546L11.2353 14.5366L10.8144 15.0366L11.1025 15.6226C12.1382 17.7271 14.2916 19.8594 16.416 20.894L17.0039 21.1802L17.5019 20.7573L20.539 18.1714L20.54 18.1724L20.541 18.1714L20.5449 18.1685C20.6832 18.0762 20.8423 18.0197 21.0078 18.0044C21.1709 17.9893 21.3353 18.0144 21.4863 18.0776L21.4931 18.0815L27.3828 20.7202L27.3887 20.7231L27.3955 20.7261C27.5937 20.8115 27.7586 20.9589 27.8662 21.146C27.9727 21.3314 28.0165 21.546 27.9922 21.7583C27.8003 23.2097 27.0879 24.5419 25.9863 25.5063C24.8837 26.4716 23.4673 27.0031 22.0019 27.0005H22C12.6274 27.0005 5.00012 19.3731 4.99998 10.0005V9.99854Z" stroke="#BFA570" stroke-width="2"/></svg>';

		$icon = '';
		if ( $is_email ) {
			$icon = $email_svg;
		} elseif ( $is_phone ) {
			$icon = $phone_svg;
		}

		$target_attr = $target ? ' target="' . esc_attr( $target ) . '"' : '';
		$rel_attr    = ( '_blank' === $target ) ? ' rel="noopener noreferrer"' : '';

		$output .= '<li class="contact-info__item">'
			. '<a class="contact-info__link" href="' . esc_url( $href ) . '"' . $target_attr . $rel_attr . '>'
				. $icon
				. '<span class="contact-info__text">' . esc_html( $title ) . '</span>'
			. '</a>'
			. '</li>';
	endwhile;

	$output .= '</ul>';

	return $output;
}
add_shortcode( 'contact-info', 'contact_info_shortcode' );

function property_filter_shortcode() {
    ob_start();
    get_template_part('elements/partials/property-filter');
    return ob_get_clean();
}
add_shortcode('property_filter', 'property_filter_shortcode');

// Feature keywords map for property feature matching
function get_feature_keywords() {
    return [
        'beachfront'      => ['beachfront', 'front line beach', 'frontline beach'],
        'beachside'       => ['beachside', 'beach side'],
        'frontline_golf'  => ['frontline golf', 'front line golf'],
        'sea_views'       => ['sea view', 'sea views'],
        'mountain_view'   => ['mountain view', 'mountain'],
        'golf_views'      => ['golf view', 'golf views', 'close to golf', 'golf'],
        'gated_complex'   => ['gated complex', 'gated community', 'gated'],
        'security_24hr'   => ['24 hour security', '24hr security', 'security'],
        'new_development' => ['new development', 'new build'],
    ];
}

function get_feature_options() {
    return [
        'beachfront'      => 'Beachfront',
        'beachside'       => 'Beachside',
        'frontline_golf'  => 'Frontline Golf',
        'sea_views'       => 'Sea Views',
        'mountain_view'   => 'Mountain View',
        'golf_views'      => 'Golf Views',
        'gated_complex'   => 'Gated Complex',
        'security_24hr'   => '24 Hour Security',
        'new_development' => 'New Development',
    ];
}

// Check if a property matches all selected features
function property_matches_features_global( $post_id, $selected_features ) {
    if ( empty( $selected_features ) ) return true;
    $feature_keywords = get_feature_keywords();
    $rows = get_field( 'key_features', $post_id );
    if ( empty( $rows ) ) return false;
    $feature_text = implode( '|', array_column( $rows, 'feature' ) );
    foreach ( $selected_features as $selected ) {
        if ( ! isset( $feature_keywords[ $selected ] ) ) continue;
        $matched = false;
        foreach ( $feature_keywords[ $selected ] as $keyword ) {
            if ( stripos( $feature_text, $keyword ) !== false ) {
                $matched = true;
                break;
            }
        }
        if ( ! $matched ) return false;
    }
    return true;
}

add_action('pre_get_posts', function($query) {
    if (!is_admin() && $query->is_main_query()) {

        // Homepage should show properties
        if ($query->is_front_page()) {
            $query->set('post_type', 'property'); // CPT slug
            $query->set('posts_per_page', 9);     // homepage grid
        }

        // Apply filters on archive + homepage + front page
        if ($query->is_post_type_archive('property') || $query->is_home() || $query->is_front_page()) {

            $meta_query = [];
            $tax_query  = [];

            // Locations (taxonomy)
            if (!empty($_GET['locations'])) {
                $tax_query[] = [
                    'taxonomy' => 'locations',
                    'field'    => 'slug',
                    'terms'    => sanitize_text_field($_GET['locations']),
                ];
            }

            // Property type (taxonomy)
            if (!empty($_GET['property-type'])) {
                $tax_query[] = [
                    'taxonomy' => 'property-type',
                    'field'    => 'slug',
                    'terms'    => sanitize_text_field($_GET['property-type']),
                ];
            }

            // Bedrooms (ACF field)
            if (!empty($_GET['bedrooms'])) {
                $meta_query[] = [
                    'key'     => 'bedrooms',
                    'value'   => (int) $_GET['bedrooms'],
                    'compare' => '='
                ];
            }

            // Reference Number (ACF field)
            if (!empty($_GET['reference_number'])) {
                $meta_query[] = [
                    'key'     => 'reference_number',
                    'value'   => sanitize_text_field($_GET['reference_number']),
                    'compare' => 'LIKE'
                ];
            }

            // Min Price (ACF field)
            if (!empty($_GET['price_min'])) {
                $meta_query[] = [
                    'key'     => 'for_sale_price',
                    'value'   => (int) $_GET['price_min'],
                    'compare' => '>=',
                    'type'    => 'NUMERIC'
                ];
            }

            // Max Price (ACF field)
            if (!empty($_GET['price_max'])) {
                $meta_query[] = [
                    'key'     => 'for_sale_price',
                    'value'   => (int) $_GET['price_max'],
                    'compare' => '<=',
                    'type'    => 'NUMERIC'
                ];
            }

            if (!empty($tax_query)) {
                $query->set('tax_query', $tax_query);
            }
            if (!empty($meta_query)) {
                $query->set('meta_query', $meta_query);
            }

            $query->set('posts_per_page', 12);

            // Sort by option
            $sortby = isset($_GET['sortby']) ? sanitize_text_field($_GET['sortby']) : 'recent';
            switch ($sortby) {
                case 'price_asc':
                    $query->set('orderby', 'meta_value_num');
                    $query->set('meta_key', 'for_sale_price');
                    $query->set('order', 'ASC');
                    break;
                case 'price_desc':
                    $query->set('orderby', 'meta_value_num');
                    $query->set('meta_key', 'for_sale_price');
                    $query->set('order', 'DESC');
                    break;
                default: // 'recent'
                    $query->set('orderby', 'date');
                    $query->set('order', 'DESC');
                    break;
            }

            // Feature filtering via post__in (repeater fields can't use meta_query)
            $selected_features = isset($_GET['features']) && is_array($_GET['features'])
                ? array_map('sanitize_text_field', array_slice($_GET['features'], 0, 20))
                : [];

            if ( ! empty( $selected_features ) ) {
                $all_properties = get_posts([
                    'post_type'      => 'property',
                    'post_status'    => 'publish',
                    'posts_per_page' => -1,
                    'fields'         => 'ids',
                    'suppress_filters' => true,
                ]);

                $filtered_ids = array_filter( $all_properties, function( $pid ) use ( $selected_features ) {
                    return property_matches_features_global( $pid, $selected_features );
                });

                $query->set( 'post__in', ! empty( $filtered_ids ) ? array_values( $filtered_ids ) : [0] );
            }
        }
    }
});

/**
 * Ensure external gallery is stored as comma-separated string, not array
 */
function ensure_external_gallery_is_string($post_id, $xml_node, $is_update) {
    if (get_post_type($post_id) !== 'property') {
        return;
    }
    
    $gallery = get_post_meta($post_id, 'external_property_gallery', true);
    
    // If it's an array, convert to comma-separated string
    if (is_array($gallery)) {
        $gallery_string = implode(', ', array_filter($gallery));
        update_post_meta($post_id, 'external_property_gallery', $gallery_string);
    }
}
add_action('pmxi_saved_post', 'ensure_external_gallery_is_string', 10, 3);




